### ISSUE TITLE
installation of dyno fails since dynwrap is called twice

### ISSUE THREAD

**Issue by abotzki** [dynverse/dyno#33]
Hi the installation of the dyno package fails at the point where dynwrap is called again - @devel
dynfeature   (NA -> 88274ff88...) [GitHub]
dynguidel... (NA -> d177eb719...) [GitHub]
dynmethods   (NA -> fbac20a1a...) [GitHub]
dynplot      (NA -> 87717ae06...) [GitHub]
dynwrap      (NA -> dee7f681b...) [GitHub]
BH         (NA -> 1.66.0-1    ) [CRAN]
bindr      (NA -> 0.1.1       ) [CRAN]
bindrcpp   (NA -> 0.2.2       ) [CRAN]
dplyr      (NA -> 0.7.8       ) [CRAN]
fansi      (NA -> 0.4.0       ) [CRAN]
pillar     (NA -> 1.3.1       ) [CRAN]
pkgconfig  (NA -> 2.0.2       ) [CRAN]
plogr      (NA -> 0.2.0       ) [CRAN]
plyr       (NA -> 1.8.4       ) [CRAN]
praise     (NA -> 1.0.0       ) [CRAN]
purrr      (NA -> 0.2.5       ) [CRAN]
ranger     (NA -> 0.10.1      ) [CRAN]
RcppEigen  (NA -> 0.3.3.5.0   ) [CRAN]
reshape2   (NA -> 1.4.3       ) [CRAN]
stringi    (NA -> 1.2.4       ) [CRAN]
stringr    (NA -> 1.3.1       ) [CRAN]
testthat   (NA -> 2.0.1       ) [CRAN]
tibble     (NA -> 1.4.2       ) [CRAN]
tidyr      (NA -> 0.8.2       ) [CRAN]
tidyselect (NA -> 0.2.5       ) [CRAN]
utf8       (NA -> 1.1.4       ) [CRAN]
dynutils   (NA -> 051f64ef5...) [GitHub]
dynwrap    (NA -> dee7f681b...) [GitHub]
dyneval      (NA           -> 72948e12a...) [GitHub]
dynwrap      (dee7f681b... -> 887a5b927...) [GitHub]

```
...
Downloading GitHub repo dynverse/dyneval@master
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘dyneval’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded
* DONE (dyneval)
Downloading GitHub repo dynverse/dynwrap@devel
Skipping dynwrap, it is already being installed
Error in vapply(remotes, install_remote, ..., FUN.VALUE = character(1)) :
  values must be type 'character',
 but FUN(X[[2]]) result is type 'logical'
Calls: <Anonymous> ... update -> update.package_deps -> install_remotes -> vapply
Execution halted
...
```

**Comment by rcannood** [comment]
Thanks for trying out dyno! Discussing with @zouter , this seems related to r-lib/remotes#225. This is a bug from remotes that probably occurs because one package requires dynwrap@master, while another package requires dynwrap@devel. I'm changing the depending packages so that they only require dynwrap@master, since the @devel dependency was included by mistake. I'll keep you posted!

**Comment by zouter** [comment]
This should now be fixed with dynverse/dynguidelines#49 . @abotzki, can you confirm? Thanks!

**Comment by abotzki** [comment]
Hmm I just tried from scratch again: the installation stops immediately.
```
> devtools::install_github('dynverse/dyno')
Error: HTTP error 403.
  API rate limit exceeded for 35.241.173.168. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2018-12-18 14:56:52 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
```
executing ```usethis::browse_github_pat()``` does not create a token, so automated installation remains difficult.

**Comment by rcannood** [comment]
This error is because your IP address has been making too many github api requests.

A good solution would be to [create a PAT](https://github.com/settings/tokens/new?description=R:GITHUB_PAT) and add a `GITHUB_PAT=<xx_your_pat_here_xx>` entry to your `~/.Renviron` file (which you can access in Rstudio with `usethis::edit_r_environ()`).

**Comment by abotzki** [comment]
Yes, I followed the suggestion and this works when I do it manually. I will see whether I can fix this by using an ansible script. It still looks like a workaround but I also understand that the issue with the r-lib remotes is beyond your control.

**Comment by sjkoelle** [comment]
I am still getting this error even when using the authentication token.  The installation seems to have failed in the middle

... (installing)...
** testing if installed package keeps a record of temporary installation path
* DONE (patchwork)
Error: Failed to install 'unknown package' from GitHub:
  Failed to install 'unknown package' from GitHub:
  Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 73.53.46.198.

Some dynverse packages appear to have installed successfully, but I get the rate limit error if I try to restart.

**Comment by rcannood** [comment]
Your issue is definitely separate from that Alexander, so please create a separate github issue. I also don't have enough information to know what your problem is. Do you have a GITHUB_PAT defined somewhere? Could you provide the full log?

**Comment by sjkoelle** [comment]
got it resolved. thanks.
